---
title: "Assignment 5"
author: "FNU Anirudh"
date: "October 1, 2015"
output: word_document
---
Question 4

```{r,eval=TRUE}
data<- c(462,425,164,784,625,472,658,658,663,928,92,230,96,626,1277,225,150,
         320,496,157,458,933,861,174,431)
# a) Empirical CDF
fn= ecdf(data)
plot(fn)
# b) Mean and Variance
m=mean(data)
m
v=var(data)
v
# c) Median and Interquantile Range
me=median(data)
me
quantile(fn)
# d) Ratio of IQR to square root of variance
# IQR= 658-225= 433
ratio= 433/sqrt(var(data))
ratio
# e) Box Plot
boxplot(data)

```

Question 5

```{r,eval=TRUE}
samp1<- c(5.098,2.739,2.146,5.006,4.016,9.026,4.965,5.016,6.195,4.523)
samp2<- c(4.627,5.061,2.787,4.181,3.617,3.605,6.036,4.745,2.340,6.934)
samp3<- c(3.021,6.173,7.602,6.250,1.875,6.996,4.850,6.661,6.360,7.052)
samp4<- c(7.390,5.666,6.616,7.868,2.428,6.740,7.605,10.868,1.739,1.996)
# a) Box Plot of All 4 Samples
boxplot(samp1,samp2,samp3,samp4,
        horizontal = TRUE,
        names= c("Sample 1","Sample 2","Sample 3","Sample 4"),
        col= c("red","yellow","blue","green"),
        main= "Box Plot of Four Samples")
# As median and variance is different in all 4 samples hence we can say that
# samples are not from same normal distribution.
# b) 

a = rnorm(40)
b = a[1:10]
c = a[11:20]
d = a[21:30]
e = a[31:40]
boxplot(b,c,d,e,
        horizontal = TRUE,
        names= c("Sample 1","Sample 2","Sample 3","Sample 4"),
        col= c("red","yellow","blue","green"),
        main= "Box Plot of Four Samples")
# We can see that median and variance is almost equal and if we increase
# size of sample values will be much more close as all samples are from
# same normal distribution.

```


